apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: chatbot-model-image
  labels:
    app: inflightassistance
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/inflightassistance/chatbot-model